[CmdletBinding()]
param(
  [string]$OcamlExe = '',
  [string]$ZlibDll = '',
  [string]$GtkPrefix = ''
)

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$gtk = if ($GtkPrefix) { $GtkPrefix } else { 'C:\msys64\ucrt64' }
if (-not (Test-Path $gtk)) { throw "GTK3 prefix not found: $gtk (set -GtkPrefix)" }

# --- locate the OCaml decrypter --------------------------------------------
if (-not $OcamlExe) {
  $cand = @(
    ([IO.Path]::Combine($root, '..', 'ocaml', 'dist-win', 'rpgm-decrypt.exe')),
    (Join-Path $root 'rpgm-decrypt.exe')
  )
  $OcamlExe = $cand | Where-Object { Test-Path $_ } | Select-Object -First 1
}
if (-not $OcamlExe -or -not (Test-Path $OcamlExe)) { throw 'rpgm-decrypt.exe not found (pass -OcamlExe)' }
if (-not $ZlibDll) {
  $ZlibDll = @(
    (Join-Path (Split-Path $OcamlExe) 'zlib1.dll'),
    ([IO.Path]::Combine($root, '..', 'ocaml', 'dist-win', 'zlib1.dll'))
  ) | Where-Object { Test-Path $_ } | Select-Object -First 1
}
if (-not $ZlibDll -or -not (Test-Path $ZlibDll)) { throw 'zlib1.dll not found (pass -ZlibDll)' }

Write-Output "OCaml decrypter: $OcamlExe"
Write-Output "GTK3 prefix:      $gtk"

# --- app icon (scarlet neon diamond) ---------------------------------------
# Generated by tools/make_icon.ps1 into rpgm-decrypt.ico (+ .png for the GTK
# window/taskbar icon at runtime). Regenerate if missing.
$iconIco = Join-Path $root 'rpgm-decrypt.ico'
$iconPng = Join-Path $root 'rpgm-decrypt.png'
if (-not (Test-Path $iconIco) -or -not (Test-Path $iconPng)) {
  $mk = Join-Path $root 'tools\make_icon.ps1'
  if (Test-Path $mk) { & powershell -NoProfile -ExecutionPolicy Bypass -File $mk } else { Write-Warning 'make_icon.ps1 not found; building without a custom icon.' }
}

# --- assemble the GTK3 runtime into a flat staging folder ------------------
$runtime = Join-Path $root 'gtk_runtime'
if (Test-Path $runtime) { Remove-Item $runtime -Recurse -Force }
New-Item -ItemType Directory -Path $runtime | Out-Null

$gtkbin = Join-Path $gtk 'bin'
# Every mingw DLL (libgtk/libgdk/glib/cairo/pango/...). Over-copy is fine.
Get-ChildItem -Path $gtkbin -Filter '*.dll' | ForEach-Object { Copy-Item $_.FullName $runtime }

# Native loaders / modules + GObject-Introspection typelibs GTK needs at runtime.
foreach ($sub in @('lib\gdk-pixbuf-2.0', 'lib\gtk-3.0', 'lib\girepository-1.0')) {
  $src = Join-Path $gtk $sub
  if (Test-Path $src) { Copy-Item $src (Join-Path $runtime (Split-Path $sub -Parent)) -Recurse }
}
# Theme/icon/schema data.
foreach ($sub in @('share\themes', 'share\icons', 'share\glib-2.0')) {
  $src = Join-Path $gtk $sub
  if (Test-Path $src) { Copy-Item $src (Join-Path $runtime 'share') -Recurse -Force }
}
$etc = Join-Path $gtk 'etc\gtk-3.0'
if (Test-Path $etc) {
  New-Item -ItemType Directory -Path (Join-Path $runtime 'etc\gtk-3.0') | Out-Null
  Copy-Item (Join-Path $etc '*') (Join-Path $runtime 'etc\gtk-3.0') -Recurse -Force
}

# Import libraries (*.dll.a) are linker inputs, never runtime-loaded — drop them.
Get-ChildItem -Path $runtime -Recurse -Filter '*.dll.a' | Remove-Item -Force

# libcrypto-3-x64.dll / libssl-3-x64.dll: the GTK runtime's copies MUST NOT
# ship — they would shadow the ones from ruby_builtin_dlls (Windows resolves
# DLLs from the app dir first), and the MSYS2 build's compiled-in OpenSSL
# config paths don't exist, breaking TLS for Ruby's net/http (star gate).
foreach ($sslDll in @('libcrypto-3-x64.dll', 'libssl-3-x64.dll')) {
  Get-ChildItem -Path $runtime -Filter $sslDll -Recurse -ErrorAction SilentlyContinue | Remove-Item -Force
}

# --- side-by-side builtin DLLs (RubyInstaller 3.x) -------------------------
# ruby.exe embeds a manifest that declares a dependent assembly
# "ruby_builtin_dlls" (libgcc_s_seh-1.dll, libwinpthread-1.dll, libgmp-10.dll,
# etc.), which lives in <ruby>\bin\ruby_builtin_dlls\ together with a
# ruby_builtin_dlls.manifest. OCRA does NOT auto-bundle this assembly, so the
# packed exe extracts a ruby.exe whose SxS activation context can't be built
# ("Dependent Assembly ruby_builtin_dlls could not be found") and dies silently.
#
# OCRA resolves --dll paths relative to the Ruby bindir and recreates that
# relative path next to the extracted ruby.exe. So passing every file of
# ruby_builtin_dlls\ (DLLs + the .manifest) rebuilds the assembly folder in the
# extraction dir and the activation context resolves at runtime.
$rubyExe = (Get-Command ruby -ErrorAction SilentlyContinue).Source
$rubyBin = if ($rubyExe) { Split-Path $rubyExe } else { 'C:\Ruby33-x64\bin' }
$builtinDir = Join-Path $rubyBin 'ruby_builtin_dlls'
# Bundle the CA certificate store so net/http works on machines without a
# Ruby install (OpenSSL's compiled-in cert path only exists on dev machines).
$rubyCert = Join-Path (Split-Path $rubyBin -Parent) 'ssl\cert.pem'
if (Test-Path $rubyCert) {
  Copy-Item $rubyCert (Join-Path $root 'cacert.pem') -Force
  Write-Output "Bundled CA certs from: $rubyCert"
} else {
  Write-Warning "Ruby CA cert store not found at $rubyCert - HTTPS (star gate) may fail."
}
$ocraExtra = @()
if (Test-Path $builtinDir) {
  Write-Output "Bundling ruby_builtin_dlls from: $builtinDir"
  Get-ChildItem -Path $builtinDir -File | ForEach-Object {
    # Forward slashes + the ruby_builtin_dlls/ prefix are what OCRA expects.
    $ocraExtra += '--dll'
    $ocraExtra += "ruby_builtin_dlls/$($_.Name)"
  }
} else {
  Write-Warning "ruby_builtin_dlls not found under $rubyBin - packed .exe may fail to start with a SideBySide error."
}

# --- run OCRA (Ruby + gtk3 gem only) ---------------------------------------
# The GTK3 runtime (ucrt64) must be on PATH and the GObject-Introspection
# typelibs reachable so the training run can `require 'gtk3'`. RPGM_GUI_BUILD=1
# tells main.rb to skip the Gtk.main loop during the build-time training pass.
# OCRA 1.3.11 predates Ruby 3.3.12, whose $LOADED_FEATURES contains a phantom
# "fiber.so" (built into the interpreter, no file on disk): pristine OCRA dies
# with Errno::ENOENT on <script dir>\fiber.so mid-build. patch_ocra.rb adds a
# File.exist? guard to OcraBuilder#createfile — idempotent, byte-exact, aborts
# loudly if the gem layout ever changes. See tools/patch_ocra.rb for details.
ruby (Join-Path $root 'tools\patch_ocra.rb')
if ($LASTEXITCODE -ne 0) { throw 'patch_ocra.rb failed' }

Write-Output 'Running OCRA...'
$env:PATH = "$gtkbin;$env:PATH"
$env:GI_TYPELIB_PATH = ([IO.Path]::Combine($gtk, 'lib', 'girepository-1.0'))
$env:GTK_PATH = $gtk
$env:RPGM_GUI_BUILD = '1'
# --add-all-core: OCRA 1.3.11's auto-detection misses core stdlib files that
# Ruby 3.3 loads very early via gem_prelude (e.g. rubygems/core_ext/
# kernel_require.rb), so the packed ruby.exe would die at startup with
# "No such file - .../rubygems/core_ext/kernel_require.rb". Bundling the full
# Ruby core library makes the packed interpreter self-sufficient.
#
# --gem-full: the ruby-gnome gems (gdk3/gtk3/...) lazily `require` extra files
# (e.g. gdk3/event-readers) only when Gtk.init runs. The build-time training
# pass sets RPGM_GUI_BUILD=1 and skips Gtk.init, so OCRA's dependency tracer
# never sees those files and would omit them (runtime LoadError). Packing the
# gems in full guarantees every gem file is present.
# --windows: build the packed exe for the Windows GUI subsystem so launching
# it does NOT pop up a black console window (professional, self-contained app).
$iconArgs = if (Test-Path $iconIco) { @('--icon', $iconIco) } else { @() }
# One retry as belt-and-braces: hosted-runner antivirus real-time scans have
# been observed killing the stub-writing ruby process (silent exit 1) even
# with Defender exclusions in place; the fiber.so crash above fails
# deterministically and is fixed by patch_ocra.rb instead.
$ocraOk = $false
foreach ($attempt in 1..2) {
  if ($attempt -gt 1) { Write-Output 'Retrying OCRA after failure...' }
  ruby -S ocra (Join-Path $root 'main.rb') --output (Join-Path $root 'rpgm-decrypt-gui.exe') --windows @iconArgs --add-all-core --gem-full @ocraExtra
  if ($LASTEXITCODE -eq 0) { $ocraOk = $true; break }
}
if (-not $ocraOk) { throw "ocra failed twice (exit $LASTEXITCODE)" }

# --- assemble the flat dist folder -----------------------------------------
$dist = Join-Path $root 'dist'
if (Test-Path $dist) { Remove-Item $dist -Recurse -Force }
New-Item -ItemType Directory -Path $dist | Out-Null

Copy-Item (Join-Path $root 'rpgm-decrypt-gui.exe') $dist
# Window/taskbar icon loaded at runtime by main.rb (from EXE_DIR).
if (Test-Path $iconPng) { Copy-Item $iconPng $dist }
if (Test-Path $iconIco) { Copy-Item $iconIco $dist }
# CA store used by net/http via SSL_CERT_FILE (see main.rb).
if (Test-Path (Join-Path $root 'cacert.pem')) { Copy-Item (Join-Path $root 'cacert.pem') $dist }
# Flatten the GTK runtime next to the .exe so EXE_DIR/PATH/GTK_PATH resolve it.
Get-ChildItem -Path $runtime | ForEach-Object { Copy-Item $_.FullName $dist -Recurse -Force }
# The decrypter pair goes LAST: the GTK runtime also ships its own zlib1.dll,
# which would otherwise overwrite the one linked against rpgm-decrypt.exe.
Copy-Item $OcamlExe $dist -Force
Copy-Item $ZlibDll $dist -Force

# --- end-user quick start (shipped inside the zip) --------------------------
$readme = @'
rpgm-decrypt GUI — quick start
==============================

1. Extract the WHOLE folder somewhere you can write (Desktop, Documents...).
   Do not run straight from inside the zip and avoid Program Files.
2. Double-click rpgm-decrypt-gui.exe.
   - First launch asks you to sign in with GitHub and star the project once
     (internet needed that one time only; afterwards it works offline).
   - Windows SmartScreen may warn about an unknown publisher: click
     "More info" -> "Run anyway". The app is open source and unsigned.
3. "Whole game" tab: pick the game folder + an EMPTY output folder, press
   Decrypt game. You get a ready-to-play decrypted copy of the game.
   "Single file" decrypts one selected asset into decrypted_cache\.
4. The Key row stays on "auto" for most games (the key is found
   automatically). Manual hex key / VX Ace seed / key-list file are there
   for unusual cases.

Everything needed ships in this folder (GTK runtime included); nothing is
installed and no other downloads are required. Logs can be saved with
"Save log...". Original game files are never modified: output always goes
to the folder you pick (the "Restore in place" button is the one
exception and it makes a .bak backup first).
'@
$ReadmePath = Join-Path $dist 'README.txt'
Set-Content -Path $ReadmePath -Value $readme -Encoding UTF8

# --- package the zip -------------------------------------------------------
# The zip contains ONE folder (rpgm-decrypt-gui/...), so extracting it never
# scatters thousands of GTK runtime files across the user's directory.
# Entries are written explicitly via ZipArchive: forward-slash names (both
# Compress-Archive and .NET Framework's ZipFile.CreateFromDirectory emit
# backslash names that some unzip tools flatten into weird files) + deflate.
$zip = Join-Path $root 'rpgm-decrypt-gui-windows-x64.zip'
if (Test-Path $zip) { Remove-Item $zip -Force }
$stage = Join-Path $root '_zip_stage'
if (Test-Path $stage) { Remove-Item $stage -Recurse -Force }
New-Item -ItemType Directory -Path (Join-Path $stage 'rpgm-decrypt-gui') | Out-Null
Copy-Item (Join-Path $dist '*') (Join-Path $stage 'rpgm-decrypt-gui') -Recurse -Force
Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem
$fs = [System.IO.File]::Open($zip, [System.IO.FileMode]::Create)
$arc = New-Object System.IO.Compression.ZipArchive($fs, [System.IO.Compression.ZipArchiveMode]::Create)
try {
  Get-ChildItem -Path $stage -Recurse -File | ForEach-Object {
    $rel = $_.FullName.Substring($stage.Length).TrimStart('\').Replace('\', '/')
    [void][System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile(
      $arc, $_.FullName, $rel, [System.IO.Compression.CompressionLevel]::Optimal)
  }
} finally {
  $arc.Dispose()
  $fs.Dispose()
}
Remove-Item $stage -Recurse -Force
Write-Output "Created $zip"
